accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("ورود-ثبت-نام/", views.login_view, name="login"),
    path("وارد-کردن-رمز-یک-بار-مصرف/", views.input_otp, name="input_otp"),
    path("چک-کردن-رمز-یک-بار-مصرف/", views.verify_otp, name="verify_otp"),
    path("جک-کردن-کاربر/", views.check_user, name="check_user"),
    path("ساخت-کاربر-جدید/", views.create_new_user, name="create_new_user"),
    path("خوش-آمدید/", views.new_user_view, name="welcome"),
    path("خروج/", views.logout_view, name="logout"),
    path("اطلاعات-کاربر/", views.main_profile_view, name="main_profile"),
    path("امتیارات-کاربر/", views.user_profile_score, name="profile_scores"),
    path("ساخن-کد-تخفیف/<int:amount>/", views.create_code, name="generate_discount_code"),
    path("تیکت-پشتیبانی-کاربر/", views.user_profile_tickets, name="user_tickets"),
    path("جزییات-تیکت-پشتیبانی/<int:ticket_id>/", views.profile_ticket_details, name="profile_ticket_details"),
    path("update-user-information/", views.save_profile_information, name="update_profile"),
    path("delete-account/", views.delete_account, name="delete_account"),
    path("orders/", views.profile_orders, name="profile_orders"),
    path("order-details/<int:order_id>/<str:track_id>/", views.user_profile_order_details, name="user_profile_order_details"),
    path("profile/محصولات-مورد-علاقه", views.user_profile_favorites, name="user_profile_favorites"),
    path("profile/لینک-دعوت-دوستان/", views.user_profile_refer_code, name="user_profile_refer_code"),
]

fapo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from accounts.sitemaps import StaticAccountsView
from blog.sitemaps import BlogPostsSitemap, BlogCommentsSitemap
from shop.sitemaps import CategorySitemap, ProductSitemap
from offers.sitemaps import OffersSitemap
from pages.sitemaps import PagesSiteMap
sitemaps = {
    "blog_posts": BlogPostsSitemap,
    "blog_comments": BlogCommentsSitemap,
    "accounts": StaticAccountsView,
    "shop_category": CategorySitemap,
    "products": ProductSitemap,
    "offers": OffersSitemap,
    "pages": PagesSiteMap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path("order/", include("orders.urls", namespace="orders")),  # Ensure `app_name` is set in `orders.urls`
    path("", include("pages.urls")),  # Home or general pages
    path("accounts/", include("accounts.urls", namespace="accounts")),  # Accounts app
    path("social-auth/", include("social_django.urls", namespace="social")),  # Social auth
    path("cart/", include("cart.urls", namespace="cart")),  # Shopping cart
    path("cities/", include("cities.urls", namespace="cities")),  # Cities app
    path("sms/", include("sms.urls", namespace="sms")),  # SMS app
    path("ticket/", include("tickets.urls", namespace="tickets")),  # Tickets app
    path("blog/", include("blog.urls", namespace="blog")),  # Blog app
    path("shop/", include("shop.urls", namespace="shop")),  # Shop app
    path("staff/", include("staff_area.urls", namespace="staff_area")),  # Staff area
    path("offers/", include("offers.urls", namespace="offers")),  # Offers app
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

offers/urls.py
from django.urls import path
from . import views

app_name = "offers"

urlpatterns = [
    path("", views.offer_list, name="offer_list"),
    path("جشنواره/<int:offer_id>", views.offer_detail, name="offer_detail"),
]

pages/urls.py
from django.urls import path
from . import views

app_name = "pages"

urlpatterns = [
    path("", views.index_page, name="index"),
    path("privacy-policy/", views.privacy_policy, name="privacy_policy"),
    path("سوالات-متداول/", views.frequency_asked_questions, name="frequency_asked_questions"),
    path("تماس-با-ما/", views.contact, name="contact"),
    path("قوانین-و-مقررات/", views.terms, name="terms"),
    path("درباره-ما/", views.about_us, name="about_us"),
    path("robots.txt", views.robots, name="robots_txt"),
]

sms/urls.py
from django.urls import path
from .views import send_otp

app_name = "sms"

urlpatterns = [
    path("send-otp/", send_otp, name="send_otp"),
]

staff_area/urls.py
from django.urls import path
from . import views


app_name = "staff_area"

urlpatterns = [
    path("", views.main_admin_view, name="main"),
    path("get-data/", views.get_new_data, name="get_data"),
    path("orders-list/", views.main_orders_admin_view, name="orders_list"),
    path("tickets-list/", views.main_tickets_admin_view, name="tickets_list"),
    path("offers/", views.main_offers_admin_view,name="offers"),
    path("ticket-details/<int:ticket_id>/", views.ticket_details_admin_view,name="ticket_details"),
    path("order-details/<int:order_id>/", views.order_details_admin_view,name="order_details"),
    path("print-address/<int:order_id>/", views.print_address, name="print_address"),
]

tickets/urls.py
from django.urls import path
from . import views

from . import views

app_name = "tickets"

urlpatterns = [
    path("add-response/<int:ticket_id>/", views.add_comment_to_ticket_profile, name="add_comment_to_ticket_profile"),
    path("close-ticket/<int:ticket_id>/", views.close_ticket_profile, name="close_ticket"),
]

staff_area/views.py
from django.shortcuts import render
from tickets.models import Tickets
from orders.models import Order, Payment
from offers.models import Offer
from django.contrib.admin.views.decorators import staff_member_required
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from shop.models import ProductsProfit
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from offers.forms import OfferForm
from tickets.forms import TicketResponseForm
from orders.tasks import send_follow_up_code, send_offers
from blog.persian_date_convert import convert_date_persian_numbers


def ret_profit():
    try:
        profit = ProductsProfit.objects.get(id=1)
    except ProductsProfit.DoesNotExist:
        profit = None
    return profit


def paginate_results_list(request, queryset, num_items=20):
    paginator = Paginator(queryset, num_items)
    page_number = request.GET.get("page", 1)

    try:
        results = paginator.page(page_number)
    except (EmptyPage, PageNotAnInteger):
        results = paginator.page(1)
    return results


@staff_member_required
@require_POST
def get_new_data(request):
    len_active_offers = Offer.objects.filter(is_active=True).count()
    len_new_orders = Order.objects.filter(status=Order.OrderChoices.PROCESSIONING).count()
    len_active_tickets = Tickets.objects.exclude(status=Tickets.TicketStatus.CLOSED).count()
    return JsonResponse({
        "status": "ok",
        "active_offers": len_active_offers,
        "active_tickets": len_active_tickets,
        "active_orders": len_new_orders
    })


@staff_member_required
def main_admin_view(request):
    profit = ret_profit()
    tickets = Tickets.objects.exclude(status=Tickets.TicketStatus.CLOSED)[:5]
    orders = Order.objects.filter(status=Order.OrderChoices.PROCESSIONING).order_by("-updated")[:5]
    offers = Offer.objects.filter(is_active=True)[:5]

    return render(request, "staff_area/main_staff.html", {
        "section": "main",
        "profit": profit,
        "tickets": tickets,
        "offers": offers,
        "orders": orders,
    }
                  )


@staff_member_required
def main_orders_admin_view(request):
    orders = Order.objects.all()
    orders = paginate_results_list(request, queryset=orders)
    profit = ret_profit()
    return render(request, "staff_area/main_staff.html", {
        "section": "orders",
        "orders": orders,
        "profit": profit,
    })


@staff_member_required
def main_tickets_admin_view(request):
    tickets = Tickets.objects.exclude(status=Tickets.TicketStatus.CLOSED).order_by("-updated")
    tickets = paginate_results_list(request, queryset=tickets)
    profit = ret_profit()

    return render(request, "staff_area/main_staff.html",
                  {"section": "tickets", "tickets": tickets, "profit": profit}
                  )


@staff_member_required
def main_offers_admin_view(request):
    profit = ret_profit()
    offers = Offer.objects.all()
    offers = paginate_results_list(request=request, queryset=offers)
    form = OfferForm()
    if request.method == 'POST':
        form = OfferForm(request.POST, request.FILES)
        if form.is_valid():
            offer_instance = form.save()
            offer_start_date = form.cleaned_data['start_date'].date()
            offer_end_date = form.cleaned_data['end_date'].date()
            offer_start_date = convert_date_persian_numbers(offer_start_date)
            offer_end_date = convert_date_persian_numbers(offer_end_date)
            message = (
                f"سلام در جشنواره {offer_instance.name} "
                f"از تاریخ {offer_start_date} تا {offer_end_date} "
                f"با وارد کردن کد {offer_instance.code} "
                f"در سبد خرید به میزان {offer_instance.discount_amount} درصد تخفیف دریافت کنید. "
                f"منتظر شما در فاپو شاپ هستیم. "
                f"https://fapo-shop.ir"
            )
            if offer_instance.image and offer_instance.image != "":
                send_offers.delay(message= message, title=offer_instance.name)
    return render(request, "staff_area/main_staff.html",
                  {
                      "section": "events",
                      "form": form,
                      "offers": offers,
                      "profit": profit,
                  }
                  )


@staff_member_required
def ticket_details_admin_view(request, ticket_id):
    profit = ret_profit()
    form = TicketResponseForm()
    try:
        ticket = Tickets.objects.get(id=ticket_id)
    except Tickets.DoesNotExist:
        ticket = None

    return render(request, "staff_area/main_staff.html",
                  {"section": "ticket", "form": form, "ticket": ticket, "profit": profit, })


@staff_member_required
def order_details_admin_view(request, order_id):
    profit = ret_profit()
    try:
        order = Order.objects.get(id=order_id)
    except Order.DoesNotExist:
        order = None
    if order:
        payment = Payment.objects.get(order=order)
        if request.method == "POST":
            follow_up_code = request.POST["follow_up_code"]
            if follow_up_code:
                order.post_follow_up = follow_up_code
                order.status = Order.OrderChoices.SEND
                order.save()
                send_follow_up_code.delay(order_id=f"{order.id}/{order.track_id}", user_id=order.user.id,
                                          track_code=follow_up_code)
    else:
        payment = None
    return render(request, "staff_area/main_staff.html",
                  {"order": order, "section": "order", "profit": profit, "payment": payment})


@staff_member_required
def print_address(request, order_id):
    try:
        order = Order.objects.get(id=order_id)
    except Order.DoesNotExist:
        order = None
    if order:
        return render(request, 'staff_area/print_address.html', {"order": order})

templates/staff_area/admin_tickets_list.html
{% load site_tags %}
<div class="ui-box" id="information-section">
    <div class="ui-box-item ui-box-white">
        <div class="ui-box-item-title ui-box-item ui-box-white">
            <div class="d-flex justify-content-between align-items-center ui-box-item ui-box-white p-2">
                <h4 class="fw-bold pb-5 pt-5">
                     تیکت های پشتیبانی :
                </h4>
                <button
                        class="btn btn-sm main-color-one-bg waves-effect waves-light"
                        href="" onclick="loadForm()">ثبت تیکت جدید
                </button>

            </div>
        <div class="ui-box-item ui-box-white bg-warning mt-2">
            <p class="font-15 p-2">لطفا قبل از ثبت تیکت جدید قسمت <a href="{% url 'pages:frequency_asked_questions' %}"><strong>سوالات متداول</strong></a> را مطالعه کنید</p>
        </div>

            <div class="responsive-table p-0">
            {% if tickets %}
                <table class="table main-table rounded-0">
                    <thead class="text-bg-dark bg-opacity-75 text-center">
                    <tr>
                        <th>ردیف</th>
                        <th>شماره پیگیری</th>
                        <th>عنوان</th>
                        <th>وضعیت</th>
                        <th>اخرین به روز رسانی</th>
                        <th>دیدن تیکت</th>

                    </tr>
                    </thead>
                    <tbody class="text-center">
                    {% for item in tickets %}
                        <tr>
                            <td class="font-14">{{ forloop.counter }}</td>
                            <td class="font-14">{{ item.id }}</td>
                            <td class="font-14">{{ item.title }}</td>
                            {% if item.status == "pending" %}
                                <td class="font-14"><span
                                        class="badge bg-secondary rounded-0 ms-2">{{ item.get_status_display }}</span>
                                </td>
                            {% elif item.status == "approved" %}
                                <td class="font-14"><span
                                        class="badge bg-success rounded-0 ms-2">{{ item.get_status_display }}</span>
                                </td>
                            {% elif item.status == "closed" %}
                                <td class="font-14"><span
                                        class="badge bg-danger rounded-0 ms-2">{{ item.get_status_display }}</span>
                                </td>
                            {% endif %}
                            <td class="font-14">{{ item.updated.date|convert_to_persian_date }} - {{ item.updated.time|time_convertor }}
                            </td>
                            <td class="align-middle text-center"><a
                                    href="{% url 'staff_area:ticket_details' ticket_id=item.id %}"
                                    class="btn main-color-three-bg shadow-none btn-sm">
                                <i class="bi bi-eye me-1 text-white"></i> نمایش</a>
                            </td>


                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                 <p class="font-14 p-3">در حال حاضر شما تیکت پشتیبانی ندارید</p>
            {% endif %}
            </div>
        </div>
    </div>
    {% if user_tickets.has_previous or user_tickets.has_next %}
    <div class="my-paginate mt-5 p-3">
        <nav aria-label="Page navigation example">
            <ul class="pagination flex-wrap justify-content-center">
                {% if user_tickets.has_previous %}
                    <li class="page-item p-2">
                        <a class="page-link rounded-3" href="?page={{ user_tickets.previous_page_number }}">قبلی</a>
                    </li>
                {% else %}
                    <li class="page-item disabled p-2">
                        <a class="page-link rounded-3" href="#">قبلی</a>
                    </li>
                {% endif %}
                {% for page_num in user_tickets.paginator.page_range %}
                    {% if page_num == user_tickets.number %}
                        <li class="page-item active"><a class="page-link rounded-3" href="#">{{ page_num }}</a>
                        </li>
                    {% else %}
                        <li class="page-item"><a class="page-link rounded-3"
                                                 href="?page={{ page_num }}">{{ page_num }}</a></li>
                    {% endif %}

                {% endfor %}
                {% if user_tickets.has_next %}
                    <li class="page-item p-2">
                        <a class="page-link rounded-3" href="?page={{ user_tickets.next_page_number }}">بعدی</a>
                    </li>
                {% else %}
                    <li class="page-item disabled p-2">
                        <a class="page-link rounded-3" href="#">بعدی</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endif %}
    


    <!-- end content -->


    <!-- start footer -->

</div>
<script>
    function loadForm() {
        const info = document.getElementById("information-section");
        const formDiv = document.getElementById("address-from");
        info.classList.add("hidden");
        formDiv.classList.remove("hidden");
    }
</script>

templates/staff_area/main_details.html
{% load site_tags %}
{% load humanize %}
{% load tz %}
<div class="ui-box-item ui-box-white ">
    <div class="ui-box-item-title pb-5">
        <div class="d-flex justify-content-between align-items-center">
            <h4 class="fw-bold pb-5">
                تیکت ها :
            </h4>
            <button
                    class="btn btn-sm main-color-one-bg waves-effect waves-light"
                    href="">مشاهده همه
            </button>
        </div>

        <div class="responsive-table p-0">
            <table class="table main-table rounded-0">
                <thead class="text-bg-dark bg-opacity-75 text-center">
                <tr>
                    <th>ردیف</th>
                    <th>شماره پیگیری</th>
                    <th>عنوان</th>
                    <th>وضعیت</th>
                    <th>اخرین به روز رسانی</th>
                    <th>دیدن تیکت</th>

                </tr>
                </thead>
                <tbody class="text-center">
                {% for item in tickets %}
                    <tr>
                        <td class="font-14">{{ forloop.counter }}</td>
                        <td class="font-14">{{ item.id }}</td>
                        <td class="font-14">{{ item.title }}</td>
                        {% if item.status == "pending" %}
                            <td class="font-14"><span
                                    class="badge bg-secondary rounded-0 ms-2">{{ item.get_status_display }}</span>
                            </td>
                        {% elif item.status == "approved" %}
                            <td class="font-14"><span
                                    class="badge bg-success rounded-0 ms-2">{{ item.get_status_display }}</span>
                            </td>
                        {% elif item.status == "closed" %}
                            <td class="font-14"><span
                                    class="badge bg-danger rounded-0 ms-2">{{ item.get_status_display }}</span>
                            </td>
                        {% endif %}
                        
                        <td class="font-14">{{ item.updated.date|convert_to_persian_date }}
                            - {{ item.updated.time|time_convertor }}
                        </td>
                        <td class="align-middle text-center"><a
                                href="{% url 'staff_area:ticket_details' ticket_id=item.id %}"
                                class="btn main-color-three-bg shadow-none btn-sm">
                            <i class="bi bi-eye me-1 text-white"></i> نمایش</a>
                        </td>


                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
    <div class="ui-box-item-title">
        <div class="d-flex justify-content-between align-items-center">
            <h4 class="fw-bold pb-5">
                جشنواره ها :
            </h4>
            <button
                    class="btn btn-sm main-color-one-bg waves-effect waves-light"
                    href="">مشاهده همه
            </button>
        </div>

        <div class="responsive-table p-0">
            <table class="table main-table rounded-0">
                <thead class="text-bg-dark bg-opacity-75 text-center">
                <tr>
                    <th>ردیف</th>
                    <th>نام</th>
                    <th>کد تخفیف</th>
                    <th>تاریخ شروع</th>
                    <th>تاریخ پایان</th>
                    <th>میزان کد تخفیف</th>
                    <th>دیدن تیکت</th>

                </tr>
                </thead>
                <tbody class="text-center">
                {% for item in offers %}
                    <tr>
                        <td class="font-14">{{ forloop.counter }}</td>
                        <td class="font-14">{{ item.name }}</td>
                        <td class="font-14">{{ item.code }}</td>
                        <td class="font-14">{{ item.start_date.date|convert_to_persian_date }}</td>
                        <td class="font-14">{{ item.end_date.date|convert_to_persian_date }}</td>
                        <td class="font-14">{{ item.discount_amount }} %
                        </td>
                        <td class="align-middle text-center"><a
                                href="{% url 'offers:offer_detail' offer_id=item.id %}"
                                class="btn main-color-three-bg shadow-none btn-sm">
                            <i class="bi bi-eye me-1 text-white"></i> نمایش</a>
                        </td>


                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
    <div class="ui-box-item-title">
        <div class="d-flex justify-content-between align-items-center">
            <h4 class="fw-bold pb-5">
                سفارش ها :
            </h4>
            <button
                    class="btn btn-sm main-color-one-bg waves-effect waves-light"
                    href="">مشاهده همه
            </button>
        </div>

        <div class="responsive-table p-0">
            <table class="table main-table rounded-0">
                <thead class="text-bg-dark bg-opacity-75 text-center">
                <tr>
                    <th>ردیف</th>
                    <th>شماره سفارش</th>
                    <th>تاریخ سفارش</th>
                    <th>مبلغ سفارش</th>
                    <th>دیدن سفارش</th>

                </tr>
                </thead>
                <tbody class="text-center">
                {% for item in orders %}
                    <tr>
                        <td class="font-14">{{ forloop.counter }}</td>
                        <td class="font-14">{{ item.id }}/{{ item.track_id }}</td>
                        <td class="font-14">{{ item.created.date|convert_to_persian_date }}</td>
                        <td class="font-14">{{ item.get_total_cost|intcomma }} تومان</td>
                        <td class="align-middle text-center"><a
                                href="{% url 'accounts:profile_ticket_details' ticket_id=item.id %}"
                                class="btn main-color-three-bg shadow-none btn-sm">
                            <i class="bi bi-eye me-1 text-white"></i> نمایش</a>
                        </td>


                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>


<!-- end content -->


<!-- start footer -->



templates/staff_area/ticket_details.html
{% load  site_tags %}

<div class="container-fluid">
    <div class="content">
        <div class="container-fluid">
            <div class="col-lg-12">

                <div class="title-panel">

                    <div class="d-flex align-items-baseline">

                        <div class="ticket-status me-4">
                            <span class="bg-secondary badge rounded-0 font-14 me-4">وضعیت تیکت : {{ ticket.get_status_display }}</span>
                            <span class="text-muted font-16 fw-lighter mb-0">شماره پیگیری : {{ ticket.id }}</span>
                        </div>
                        <div class="ticket-status me-4">
                            <span class="bg-success badge rounded-0 font-14 me-4">عنوان تیکت : {{ ticket.title }}</span>
                        </div>
                        <div class="ticket-created-at me-4">
                            <i class="bi bi-clock me-1"></i>
                            <span>تاریخ ایجاد
                            
                                    {{ ticket.created.date|convert_to_persian_date }} ساعت
                                    {{ ticket.created.time|time_convertor }}
                             
                            </span>
                        </div>

                    </div>
                </div>
                <div class="ticket-message">
                    <h6 class="font-16">
                        کاربر:
                        {% if ticket.user.profile.first_name %}
                            {{ ticket.user.profile.first_name }} {{ ticket.user.profile.last_name }}
                        {% elif ticket.user.phone_number %}
                            {{ ticket.user.phone_number }}
                        {% else %}
                            {{ ticket.user.email }}
                        {% endif %}
                    </h6>
                    <h6 class="font-16">
                        متن تیکت :
                    </h6>

                    <!-- Messages-->
                    <div class="comment  shadow-none user">
                        <div class="comment-author-ava"><i
                                class="fa-regular fa-2x fa-user p-3"></i></div>
                        <div class="comment-body">
                            <p class="comment-text">{{ ticket.description }}
                            </p>
                            <div class="comment-footer"><span class="comment-meta"></span>
                                <div class="comment-date float-end"><span
                                        class="comment-meta">{{ ticket.created.date|convert_to_persian_date }} ساعت {{ ticket.created.time|time_convertor }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% if ticket.response %}
                        {% for item in ticket.response.all %}
                            <div class="comment  shadow-none {% if item.user.is_staff %}active{% endif %}">
                                <div class="comment-author-ava"><i
                                        class="fa-regular fa-2x fa-user p-3"></i></div>
                                <div class="comment-body">
                                    <p class="comment-text">{{ item.response }}
                                    </p>
                                    <div class="comment-footer"><span class="comment-meta">{% if item.user.is_staff %}
                                        پاسخ پشتیبان  {% else %}  پاسخ کاربر {% endif %}</span>
                                        <div class="comment-date float-end"><span
                                                class="comment-meta">
                                           
                                                {{ item.created.date|convert_to_persian_date }} ساعت
                                                {{ item.created.time|time_convertor }}
                                        
                                        </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% endif %}
                    <div class="d-flex justify-content-end">
                        <a href="{% url 'tickets:close_ticket' ticket_id=ticket.id %}"
                           class="btn btn-danger">
                            بستن تیکت
                        </a>
                    </div>
                    <h5 class="mb-3">ارسال پیام</h5>
                    <form method="post"
                          action="{% url 'tickets:add_comment_to_ticket_profile' ticket_id=ticket.id %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="{{ form.response.id_for_label }}"></label><textarea
                                name="{{ form.response.name }}" class="form-control form-control-rounded"
                                id="{{ form.response.id_for_label }}" rows="8"
                                placeholder="پیام خود را وارد کنید..." required=""></textarea>
                        </div>
                        <div class="text-right">
                            <button class="btn border-0 main-color-one-bg"
                                    type="submit">ارسال پیام
                            </button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>


