accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("ورود-ثبت-نام/", views.login_view, name="login"),
    path("وارد-کردن-رمز-یک-بار-مصرف/", views.input_otp, name="input_otp"),
    path("چک-کردن-رمز-یک-بار-مصرف/", views.verify_otp, name="verify_otp"),
    path("جک-کردن-کاربر/", views.check_user, name="check_user"),
    path("ساخت-کاربر-جدید/", views.create_new_user, name="create_new_user"),
    path("خوش-آمدید/", views.new_user_view, name="welcome"),
    path("خروج/", views.logout_view, name="logout"),
    path("اطلاعات-کاربر/", views.main_profile_view, name="main_profile"),
    path("امتیارات-کاربر/", views.user_profile_score, name="profile_scores"),
    path("ساخن-کد-تخفیف/<int:amount>/", views.create_code, name="generate_discount_code"),
    path("تیکت-پشتیبانی-کاربر/", views.user_profile_tickets, name="user_tickets"),
    path("جزییات-تیکت-پشتیبانی/<int:ticket_id>/", views.profile_ticket_details, name="profile_ticket_details"),
    path("update-user-information/", views.save_profile_information, name="update_profile"),
    path("delete-account/", views.delete_account, name="delete_account"),
    path("orders/", views.profile_orders, name="profile_orders"),
    path("order-details/<int:order_id>/<str:track_id>/", views.user_profile_order_details, name="user_profile_order_details"),
    path("profile/محصولات-مورد-علاقه", views.user_profile_favorites, name="user_profile_favorites"),
    path("profile/لینک-دعوت-دوستان/", views.user_profile_refer_code, name="user_profile_refer_code"),
]

fapo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from accounts.sitemaps import StaticAccountsView
from blog.sitemaps import BlogPostsSitemap, BlogCommentsSitemap
from shop.sitemaps import CategorySitemap, ProductSitemap
from offers.sitemaps import OffersSitemap
from pages.sitemaps import PagesSiteMap
sitemaps = {
    "blog_posts": BlogPostsSitemap,
    "blog_comments": BlogCommentsSitemap,
    "accounts": StaticAccountsView,
    "shop_category": CategorySitemap,
    "products": ProductSitemap,
    "offers": OffersSitemap,
    "pages": PagesSiteMap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path("order/", include("orders.urls", namespace="orders")),  # Ensure `app_name` is set in `orders.urls`
    path("", include("pages.urls")),  # Home or general pages
    path("accounts/", include("accounts.urls", namespace="accounts")),  # Accounts app
    path("social-auth/", include("social_django.urls", namespace="social")),  # Social auth
    path("cart/", include("cart.urls", namespace="cart")),  # Shopping cart
    path("cities/", include("cities.urls", namespace="cities")),  # Cities app
    path("sms/", include("sms.urls", namespace="sms")),  # SMS app
    path("ticket/", include("tickets.urls", namespace="tickets")),  # Tickets app
    path("blog/", include("blog.urls", namespace="blog")),  # Blog app
    path("shop/", include("shop.urls", namespace="shop")),  # Shop app
    path("staff/", include("staff_area.urls", namespace="staff_area")),  # Staff area
    path("offers/", include("offers.urls", namespace="offers")),  # Offers app
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

app_name = "pages"

urlpatterns = [
    path("", views.index_page, name="index"),
    path("privacy-policy/", views.privacy_policy, name="privacy_policy"),
    path("سوالات-متداول/", views.frequency_asked_questions, name="frequency_asked_questions"),
    path("تماس-با-ما/", views.contact, name="contact"),
    path("قوانین-و-مقررات/", views.terms, name="terms"),
    path("درباره-ما/", views.about_us, name="about_us"),
    path("robots.txt", views.robots, name="robots_txt"),
]

shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path("", views.default_shop_view, name="shop"),
    path("like/", views.product_like, name="like_product"),
    path("category/", views.product_filter_by_categories , name="category"),
    path("product_detail/<int:product_id>/<str:product_slug>/", views.product_detail, name="product_detail"),
    path("check-stock/", views.quantity_of_product_with_color, name="check_stock"),
    path("search/", views.product_search, name="search"),
    path("category/<str:slug>/", views.category, name="product_list_by_category",)
]

sms/urls.py
from django.urls import path
from .views import send_otp

app_name = "sms"

urlpatterns = [
    path("send-otp/", send_otp, name="send_otp"),
]

tickets/urls.py
from django.urls import path
from . import views

from . import views

app_name = "tickets"

urlpatterns = [
    path("add-response/<int:ticket_id>/", views.add_comment_to_ticket_profile, name="add_comment_to_ticket_profile"),
    path("close-ticket/<int:ticket_id>/", views.close_ticket_profile, name="close_ticket"),
]

blog/models.py
from django.db import models
from django.utils import timezone
from accounts.models import CustomUser
from django.urls import reverse
from taggit.managers import TaggableManager
from django.utils.text import slugify



class PostCategory(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)
    icon = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ["name"]
        indexes = [
            models.Index(fields=["name"])
        ]
        verbose_name = "category"
        verbose_name_plural = "categories"

    def get_absolute_url(self):
        return reverse("blog:post_by_categories", args=[self.slug, self.id])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name, allow_unicode=True)

        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)

class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    category = models.ForeignKey(PostCategory, related_name="posts", on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    subtitle = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date="publish", allow_unicode=True)
    author = models.ForeignKey(CustomUser,
                               on_delete=models.CASCADE,
                               related_name="blog_posts")
    body = models.TextField()
    tags = TaggableManager()
    image = models.ImageField(upload_to="post_images", null=True, blank=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)

    objects = models.Manager()  # The Default Manager
    published = PublishedManager()  # Our Custom Manager

    class Meta:
        ordering = ["-publish"]
        indexes = models.Index(fields=["-publish"]),

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[
            self.slug,
            self.publish.year,
            self.publish.month,
            self.publish.day,

        ])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title, allow_unicode=True)

        super().save(*args, **kwargs)

class PostSection(models.Model):
    post = models.ForeignKey(Post, related_name="sections", on_delete=models.CASCADE)
    subtitle = models.CharField(max_length=250)
    image = models.ImageField(upload_to="post_section_images", null=True, blank=True)
    body = models.TextField()

    class Meta:
        ordering = ["id"]

    def __str__(self):
        return f"Section: {self.subtitle} (Post: {self.post.title})"

class PostComment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, related_name='comments', on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False)

    parent = models.ForeignKey('self', null=True, blank=True, related_name='replies', on_delete=models.CASCADE)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Comment by {self.user} on {self.post}'

    @property
    def is_reply(self):
        """Return True if the comment is a reply to another comment."""
        return self.parent is not None

accounts/forms.py
from django import forms
import re
from cities.models import City, State
from .models import CustomUser

class GetPhoneNumberForm(forms.Form):
    phone = forms.CharField(
        max_length=11,
        label="شماره همراه خود را وارد کنید",
        widget=forms.TextInput(attrs={'placeholder': 'مثال 09128885544'})
    )

    def clean_phone_number(self):
        phone = self.cleaned_data["phone_email"]
        if re.match(r'^\d{11}$', phone):
            return phone

        else:
            raise forms.ValidationError("شماره تلفن یا ایمیل وارد شده صحیح نمی باشد")



class ProfileForm(forms.Form):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    province = forms.ModelChoiceField(queryset=State.objects.all(), empty_label="استان خود را انتخاب کنید")
    city = forms.ModelChoiceField(queryset=City.objects.none(), empty_label="شهر خود را انتخاب کنید")
    address = forms.CharField(widget=forms.Textarea)
    zip_code = forms.CharField(max_length=10)
    email = forms.EmailField(required=False)
    phone = forms.CharField(max_length=11)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        self.fields['first_name'].label = 'نام'
        self.fields['last_name'].label = 'نام خانوادگی'
        self.fields['province'].label = 'استان'
        self.fields['city'].label = 'شهر'
        self.fields['address'].label = 'آدرس'
        self.fields['zip_code'].label = 'کد پستی'
        self.fields["email"].label = 'پست الکترونیک'
        self.fields["phone"].label = "تلفن همراه"

        if 'province' in self.data:
            try:
                state_id = int(self.data.get('province'))
                self.fields['city'].queryset = City.objects.filter(state_id=state_id).order_by('name')
                self.fields['city'].empty_label = 'شهر خود را انتخاب کنید'
            except (ValueError, TypeError):
                pass


    def clean_email(self):
        email = self.cleaned_data['email']
        if CustomUser.objects.filter(email=email).exclude(pk=self.user.pk).exists():
            raise forms.ValidationError("این پست الکترونیک قبلاً ثبت شده است.")
        return email

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if phone:
            # Exclude the current user's phone number from the uniqueness check
            if CustomUser.objects.filter(phone_number=phone).exclude(pk=self.user.pk).exists():
                raise forms.ValidationError("این شماره تلفن قبلاً ثبت شده است.")
        return phone



templates/accounts/profile/delete_account.html
{% load site_tags %}
{% load  static %}

<div class="lastest-order mt-3">
    <div class="content-box">
        <div class="ui-boxs">
            <div class="ui-box" id="information-section">
                <div class="ui-box-item ui-box-white">
                    <div class="ui-box-item-title">
                        <div class="d-flex justify-content-between align-items-center">
                            <h3 class="fw-bold">
                                حذف اکانت کاربری :
                            </h3>

                        </div>
                    </div>

                </div>
                <h6 class="text-danger p-3 fw-bold">
                    توجه کنید :
                </h6>
                <p class="p-3">
                    با حذف اکانت  تمامی امتیازات شما و تاریخچه فعالیت های شما در سایت نظیر محصولات مورد علاقه و سفارشات شما
                    از بین خواهد رفت
                </p>
                <form method="post" action="{% url 'accounts:delete_account' %}" class="px-3">
                    {% csrf_token %}
                    <div class="container">
                        <div class="row">
                            <div class="col-md-6">

                                <button type="submit" class="btn border-0 btn-danger waves-effect waves-light p-2 w-100">
                                    متن بالا را با
                                    دقت مطالعه کردم و اکانت خود را حذف میکنم
                                </button>
                               
                            </div>
                            <div class="col-md-6">

                                <a href="{% url 'accounts:main_profile' %}" class="btn border-0 btn-success waves-effect waves-light p-2 w-100">انصراف و بازگشت</a>

                            </div>
                        </div>
                    </div>
                    
                </form>
            </div>
        </div>
    </div>
</div>
{% include 'pagination.html' with products=user_discount_codes %}
 

templates/accounts/profile/refer_link.html
{% load site_tags %}

<div id="information-section">
    <div class="ui-box-item-title">
        <div class="d-flex justify-content-between align-items-center p-4">
            <h4 class="fw-bold">
                لینک دعوت شخصی شما :
            </h4>
            <button data-bs-toggle="modal" onclick="myFunction()"
                    class="btn btn-sm main-color-one-bg waves-effect waves-light" href="">
                برای کپی کردن کلیک کنید <i class="fa-solid fa-copy"></i></button>
        </div>
    </div>
    <div class="ui-box-item-desc p-5 text-center border border-1">
        <p dir="ltr" class="font-18"><strong> {{ refer_url }}</strong></p>
    </div>
    <input type="hidden" value="{{ refer_url }}" id="myInput">

    <div class="ui-box-item-desc p-5 text-center">
        <p>دوستان خودتون رو به فاپوشاپ دعوت کنید و امتیاز بگیرید !! </p>
    </div>
    <div class="ui-box-item-desc p-5 text-center border border-1"><p>
        تعداد دعوت موفق : <span class="text-success"><strong>{{ user_invites }}</strong></span></p>
        <p>
        مجموع امتیاز کسب شده با دعوت دوستان : <span class="text-success"><strong>{{ user_invites|division }}</strong></span></p>
    </div>
</div>


<script>
    function myFunction() {
        // Get the text field
        const copyText = document.getElementById("myInput");

        // Select the text field
        copyText.select();
        
        // Copy the text inside the text field
        navigator.clipboard.writeText(copyText.value);

    }
</script>

templates/accounts/profile/ticket_details.html
{% load  site_tags %}
<div class="container-fluid">
    <div class="content">
        <div class="container-fluid">
            <div class="col-lg-12">

                <div class="title-panel">

                    <div class="d-flex align-items-baseline">

                        <div class="ticket-status me-4">
                            <span class="bg-secondary badge rounded-0 font-14 me-4">وضعیت تیکت : {{ ticket.get_status_display }}</span>
                            <span class="text-muted font-16 fw-lighter mb-0">شماره پیگیری : {{ ticket.id }}</span>
                        </div>
                        <div class="ticket-status me-4">
                            <span class="bg-success badge rounded-0 font-14 me-4">عنوان تیکت : {{ ticket.title }}</span>
                        </div>
                        <div class="ticket-created-at me-4">
                            <i class="bi bi-clock me-1"></i>
                            <span>تاریخ ایجاد {{ ticket.created.date|convert_to_persian_date }} ساعت  {{ ticket.created.time|time_convertor }} </span>
                        </div>
                        {% if  ticket.created|compare_dates:user_ticket.updated %}
                            <div class="ticket-created-at me-4">
                                <i class="bi bi-arrow-left me-1"></i>
                                <span>به روز شده {{ ticket.updated.date|convert_to_persian_date }} {{ ticket.updated.time|time_convertor }} </span>
                            </div>
                        {% endif %}

                    </div>
                </div>
                <div class="ticket-message">
                    <h6 class="font-16">
                        متن تیکت :
                    </h6>
                    <!-- Messages-->
                    <div class="comment  shadow-none user">
                        <div class="comment-author-ava"><i
                                class="fa-regular fa-2x fa-user p-3"></i></div>
                        <div class="comment-body">
                            <p class="comment-text">{{ ticket.description }}
                            </p>
                            <div class="comment-footer"><span class="comment-meta"></span>
                                <div class="comment-date float-end"><span
                                        class="comment-meta">{{ ticket.created.date|convert_to_persian_date }} ساعت {{ ticket.created.time|time_convertor }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% if responses %}
                        {% for item in responses %}
                            <div class="comment  shadow-none {% if item.user.is_staff %}active{% endif %}">
                                <div class="comment-author-ava"><i
                                        class="fa-regular fa-2x fa-user p-3"></i></div>
                                <div class="comment-body">
                                    {% if item.user.is_staff %}
                                        <p class="comment-text">{{ item.response|safe }}
                                        </p>
                                    {% else %}
                                        <p class="comment-text">{{ item.response }}
                                        </p>
                                    {% endif %}
                                    <div class="comment-footer"><span class="comment-meta">{% if item.user.is_staff %}
                                        پاسخ پشتیبان  {% else %}  پاسخ کاربر {% endif %}</span>
                                        <div class="comment-date float-end"><span
                                                class="comment-meta">{{ item.created.date|convert_to_persian_date }} ساعت {{ item.created.time|time_to_persian }}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% endif %}
                    {% if ticket.status != "closed" %}
                        <div class="d-flex justify-content-end">
                            <a href="{% url 'tickets:close_ticket' ticket_id=ticket.id %}"
                               class="btn btn-danger">
                                بستن تیکت
                            </a>
                        </div>
                        <h5 class="mb-3">ارسال پیام</h5>
                        <form method="post"
                              action="{% url 'tickets:add_comment_to_ticket_profile' ticket_id=ticket.id %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="{{ form.response.id_for_label }}"></label><textarea
                                    name="{{ form.response.name }}" class="form-control form-control-rounded"
                                    id="{{ form.response.id_for_label }}" rows="8"
                                    placeholder="پیام خود را وارد کنید..." required=""></textarea>
                            </div>
                            <div class="text-right">
                                <button class="btn border-0 main-color-one-bg"
                                        type="submit">ارسال پیام
                                </button>
                            </div>
                        </form>
                    {% else %}
                        <div class="my-4">
                            <div class="alert alert-danger text-center">
                                تیکت بسته شده است و امکان ارسال پاسخ جدید وجود
                                ندارد
                            </div>
                        </div>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
</div>




templates/accounts/profile/tickets_section.html
{% load site_tags %}
<div class="ui-box" id="information-section">
    <div class="ui-box-item ui-box-white">
        <div class="ui-box-item-title ui-box-item ui-box-white">
            <div class="d-flex justify-content-between align-items-center ui-box-item ui-box-white p-2">
                <h4 class="fw-bold pb-5 pt-5">
                     تیکت های پشتیبانی شما :
                </h4>
                <button
                        class="btn btn-sm main-color-one-bg waves-effect waves-light"
                        href="" onclick="loadForm()">ثبت تیکت جدید
                </button>

            </div>
        <div class="ui-box-item ui-box-white bg-warning mt-2">
            <p class="font-15 p-2">لطفا قبل از ثبت تیکت جدید قسمت <a href="{% url 'pages:frequency_asked_questions' %}"><strong>سوالات متداول</strong></a> را مطالعه کنید</p>
        </div>

            <div class="responsive-table p-0">
            {% if user_tickets %}
                <table class="table main-table rounded-0">
                    <thead class="text-bg-dark bg-opacity-75 text-center">
                    <tr>
                        <th>ردیف</th>
                        <th>شماره پیگیری</th>
                        <th>عنوان</th>
                        <th>وضعیت</th>
                        <th>اخرین به روز رسانی</th>
                        <th>دیدن تیکت</th>

                    </tr>
                    </thead>
                    <tbody class="text-center">
                    {% for item in user_tickets %}
                        <tr>
                            <td class="font-14">{{ forloop.counter }}</td>
                            <td class="font-14">{{ item.id }}</td>
                            <td class="font-14">{{ item.title }}</td>
                            {% if item.status == "pending" %}
                                <td class="font-14"><span
                                        class="badge bg-secondary rounded-0 ms-2">{{ item.get_status_display }}</span>
                                </td>
                            {% elif item.status == "approved" %}
                                <td class="font-14"><span
                                        class="badge bg-success rounded-0 ms-2">{{ item.get_status_display }}</span>
                                </td>
                            {% elif item.status == "closed" %}
                                <td class="font-14"><span
                                        class="badge bg-danger rounded-0 ms-2">{{ item.get_status_display }}</span>
                                </td>
                            {% endif %}
                            <td class="font-14">{{ item.updated.date|convert_to_persian_date }} - {{ item.updated.time|time_convertor }}
                            </td>
                            <td class="align-middle text-center"><a
                                    href="{% url 'accounts:profile_ticket_details' ticket_id=item.id %}"
                                    class="btn main-color-three-bg shadow-none btn-sm">
                                <i class="bi bi-eye me-1 text-white"></i> نمایش</a>
                            </td>


                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                 <p class="font-14 p-3">در حال حاضر شما تیکت پشتیبانی ندارید</p>
            {% endif %}
            </div>
        </div>
    </div>
    {% if user_tickets.has_previous or user_tickets.has_next %}
    <div class="my-paginate mt-5 p-3">
        <nav aria-label="Page navigation example">
            <ul class="pagination flex-wrap justify-content-center">
                {% if user_tickets.has_previous %}
                    <li class="page-item p-2">
                        <a class="page-link rounded-3" href="?page={{ user_tickets.previous_page_number }}">قبلی</a>
                    </li>
                {% else %}
                    <li class="page-item disabled p-2">
                        <a class="page-link rounded-3" href="#">قبلی</a>
                    </li>
                {% endif %}
                {% for page_num in user_tickets.paginator.page_range %}
                    {% if page_num == user_tickets.number %}
                        <li class="page-item active"><a class="page-link rounded-3" href="#">{{ page_num }}</a>
                        </li>
                    {% else %}
                        <li class="page-item"><a class="page-link rounded-3"
                                                 href="?page={{ page_num }}">{{ page_num }}</a></li>
                    {% endif %}

                {% endfor %}
                {% if user_tickets.has_next %}
                    <li class="page-item p-2">
                        <a class="page-link rounded-3" href="?page={{ user_tickets.next_page_number }}">بعدی</a>
                    </li>
                {% else %}
                    <li class="page-item disabled p-2">
                        <a class="page-link rounded-3" href="#">بعدی</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endif %}
    


    <!-- end content -->


    <!-- start footer -->

</div>
<script>
    function loadForm() {
        const info = document.getElementById("information-section");
        const formDiv = document.getElementById("address-from");
        info.classList.add("hidden");
        formDiv.classList.remove("hidden");
    }
</script>

templates/accounts/profile/users_orders_list.html
{% load site_tags %}
{% load humanize %}

<div class="content-box">
    <div class="container-fluid">
        <div class="title-panel">
            <h6 class="font-16">
                سفارشات
            </h6>
        </div>
        <div class="responsive-table p-0">
            <table class="table main-table rounded-0">
                <thead class="text-bg-dark bg-opacity-75 text-center">
                <tr>
                    <th>#</th>
                    <th>شماره سفارش</th>
                    <th>تاریخ ثبت سفارش</th>
                    <th>مبلغ سفارش</th>
                    <th>وضعیت سفارش</th>
                    <th>جزییات</th>
                </tr>
                </thead>
                <tbody class="text-center">
                {% for order in orders %}
                    <tr>
                        <td class="font-14">{{ forloop.counter }}</td>
                        <td class="font-14">{{ order.track_id }}/ {{ order.id }}</td>
                        <td class="font-14">{{ order.created.date|convert_to_persian_date }}</td>
                        <td class="font-14">{{ order.get_total_cost|multiply:1|intcomma }} ریال</td>
                        {% if order.paid %}
                            {% if order.status == "Send" %}
                            <td class="font-14"><span
                                    class="success-label rounded-pill">{{ order.get_status_display }}</span></td>
                                {% else %}
                                <td class="font-14"><span
                                    class="warning-label rounded-pill">{{ order.get_status_display }}</span></td>
                                {% endif %}
                        {% else %}
                            <td class="font-14"><span class="danger-label rounded-pill">ناموفق</span></td>
                        {% endif %}
                        <td class="font-14">
                            <a href="{% url 'accounts:user_profile_order_details' order_id=order.id track_id=order.track_id %}"
                               class="btn btn-sm border-0 main-color-one-bg waves-effect waves-light">مشاهده <i
                                    class="bi bi-chevron-left text-white font-16"></i></a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
</div>
{% if orders.has_previous or orders.has_next %}
    <div class="my-paginate mt-5 p-3">
        <nav aria-label="Page navigation example">
            <ul class="pagination flex-wrap justify-content-center">
                {% if orders.has_previous %}
                    <li class="page-item p-2">
                        <a class="page-link rounded-3" href="?page={{ orders.previous_page_number }}">قبلی</a>
                    </li>
                {% else %}
                    <li class="page-item disabled p-2">
                        <a class="page-link rounded-3" href="#">قبلی</a>
                    </li>
                {% endif %}
                {% for page_num in orders.paginator.page_range %}
                    {% if page_num == orders.number %}
                        <li class="page-item active"><a class="page-link rounded-3" href="#">{{ page_num }}</a>
                        </li>
                    {% else %}
                        <li class="page-item"><a class="page-link rounded-3"
                                                 href="?page={{ page_num }}">{{ page_num }}</a></li>
                    {% endif %}

                {% endfor %}
                {% if orders.has_next %}
                    <li class="page-item p-2">
                        <a class="page-link rounded-3" href="?page={{ orders.next_page_number }}">بعدی</a>
                    </li>
                {% else %}
                    <li class="page-item disabled p-2">
                        <a class="page-link rounded-3" href="#">بعدی</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endif %}