fapo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from accounts.sitemaps import StaticAccountsView
from blog.sitemaps import BlogPostsSitemap, BlogCommentsSitemap
from shop.sitemaps import CategorySitemap, ProductSitemap
from offers.sitemaps import OffersSitemap
from pages.sitemaps import PagesSiteMap
sitemaps = {
    "blog_posts": BlogPostsSitemap,
    "blog_comments": BlogCommentsSitemap,
    "accounts": StaticAccountsView,
    "shop_category": CategorySitemap,
    "products": ProductSitemap,
    "offers": OffersSitemap,
    "pages": PagesSiteMap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path("order/", include("orders.urls", namespace="orders")),  # Ensure `app_name` is set in `orders.urls`
    path("", include("pages.urls")),  # Home or general pages
    path("accounts/", include("accounts.urls", namespace="accounts")),  # Accounts app
    path("social-auth/", include("social_django.urls", namespace="social")),  # Social auth
    path("cart/", include("cart.urls", namespace="cart")),  # Shopping cart
    path("cities/", include("cities.urls", namespace="cities")),  # Cities app
    path("sms/", include("sms.urls", namespace="sms")),  # SMS app
    path("ticket/", include("tickets.urls", namespace="tickets")),  # Tickets app
    path("blog/", include("blog.urls", namespace="blog")),  # Blog app
    path("shop/", include("shop.urls", namespace="shop")),  # Shop app
    path("staff/", include("staff_area.urls", namespace="staff_area")),  # Staff area
    path("offers/", include("offers.urls", namespace="offers")),  # Offers app
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

offers/urls.py
from django.urls import path
from . import views

app_name = "offers"

urlpatterns = [
    path("", views.offer_list, name="offer_list"),
    path("جشنواره/<int:offer_id>", views.offer_detail, name="offer_detail"),
]

pages/urls.py
from django.urls import path
from . import views

app_name = "pages"

urlpatterns = [
    path("", views.index_page, name="index"),
    path("privacy-policy/", views.privacy_policy, name="privacy_policy"),
    path("سوالات-متداول/", views.frequency_asked_questions, name="frequency_asked_questions"),
    path("تماس-با-ما/", views.contact, name="contact"),
    path("قوانین-و-مقررات/", views.terms, name="terms"),
    path("درباره-ما/", views.about_us, name="about_us"),
    path("robots.txt", views.robots, name="robots_txt"),
]

sms/urls.py
from django.urls import path
from .views import send_otp

app_name = "sms"

urlpatterns = [
    path("send-otp/", send_otp, name="send_otp"),
]

offers/models.py
from django.db import models
from django.contrib.auth import get_user_model
import string
import random
from django.utils.timezone import now

User = get_user_model()


class Offer(models.Model):
    name = models.CharField(max_length=255)  # Name of the event (e.g., Black Friday)
    code = models.CharField(max_length=15, unique=True, blank=True)  # Allow blank initially
    discount_amount = models.PositiveIntegerField()  # Discount value
    image = models.ImageField(upload_to='offers/', blank=True, null=True)
    start_date = models.DateTimeField()  # When the offer becomes active
    end_date = models.DateTimeField()  # When the offer expires
    is_active = models.BooleanField(default=True)  # To manually enable/disable the offer

    def __str__(self):
        return f"{self.name} ({self.code})"

    def generate_unique_code(self):
        length = 8
        characters = string.ascii_letters + string.digits
        while True:
            code = ''.join(random.choice(characters) for _ in range(length))
            if not Offer.objects.filter(code=code).exists():
                return code

    def check_offer(self):
        if self.is_active:
            today = now()
            if self.start_date <= today <= self.end_date:
                return True
            return False

    def offer_status(self):
        if self.start_date > now():
            return "پیش رو"
        if self.start_date <= now() < self.end_date:
            return "فعال"
        return "منقضی شده"

    def usage_count(self):
        return self.offerusage_set.count()

    @staticmethod
    def get_future_offers():
        """
        Returns all offers that will be active in the future.
        """
        return Offer.objects.filter(
            start_date__gt=now(),
            is_active=True,
            image__isnull=False
        ).exclude(image="")

    @staticmethod
    def get_active_offers():
        """
        Returns all currently active offers.
        """
        return Offer.objects.filter(
            start_date__lte=now(),
            end_date__gte=now(),
            is_active=True,
            image__isnull=False
        ).exclude(image="")

    @staticmethod
    def get_outdated_offers():
        """
        Returns all offers that have expired.
        """
        return Offer.objects.filter(
            end_date__lt=now(),
            image__isnull=False
        ).exclude(image="")

    def save(self, *args, **kwargs):
        if not self.code:  # Ensure the code is set only if blank
            self.code = self.generate_unique_code()
        super(Offer, self).save(*args, **kwargs)


class OfferUsage(models.Model):
    phone_identifier = models.CharField(max_length=255, null=True, blank=True)
    email_identifier = models.CharField(max_length=255, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # The user who used the offer
    offer = models.ForeignKey(Offer, on_delete=models.CASCADE)  # The offer code
    used_at = models.DateTimeField(auto_now_add=True)  # Timestamp of usage

    class Meta:
        unique_together = ('user', 'offer')

offers/forms.py
from django import forms
from django.utils import timezone
from .models import Offer


class OfferForm(forms.ModelForm):
    class Meta:
        model = Offer
        fields = ['name', 'code', 'discount_amount', 'image', 'start_date', 'end_date', 'is_active']

    # Optionally, you can add custom validation here for certain fields if necessary.
    def clean_start_date(self):
        start_date = self.cleaned_data.get('start_date')
        if start_date and start_date < timezone.now():
            raise forms.ValidationError("Start date cannot be in the past.")
        return start_date

    def clean_code(self):
        code = self.cleaned_data.get('code')
        list_code = code.split()
        persian_digits = {
            '۰': "0",
            "۱": "1",
            "۲": "2",
            "۳": "3",
            "۴": "4",
            "۵": "5",
            "۶": "6",
            "۷": "7",
            "۸": "8",
            "۹": "9",
        }
        final_code = ""
        for i in list_code:
            for key, value in persian_digits.items():
                if i == key:
                    final_code += value
            final_code += i

        return final_code

    def clean_image(self):
        image = self.cleaned_data.get('image')
        # Allow the image to be empty
        if not image:
            return None
        return image

    def clean_end_date(self):
        end_date = self.cleaned_data.get('end_date')
        start_date = self.cleaned_data.get('start_date')
        if end_date and start_date and end_date <= start_date:
            raise forms.ValidationError("End date must be after the start date.")
        return end_date

offers/views.py
from django.shortcuts import render
from .models import Offer


def offer_list(request):
    future_offers = Offer.get_future_offers()
    active_offers = Offer.get_active_offers()
    out_dated_offers = Offer.get_outdated_offers()

    return render(request, "offers/offers_list.html", {
        "offers": active_offers,
        "future_offers": future_offers,
        "out_dated_offers": out_dated_offers
    })


def offer_detail(request, offer_id):
    try:
        offer = Offer.objects.get(id=offer_id)
    except Offer.DoesNotExist:
        offer = None

    return render(request, 'offers/offer_detail.html', {"offer": offer})


templates/offers/offer_detail.html
{% extends 'base.html' %}
{% load site_tags %}
{% load static %}
{% block title %}
    جشنواره {{ offer.name }}
{% endblock %}

{% block tags %}
    <meta name="description"
  content="از تاریخ {{ offer.start_date|convert_to_persian_date }} تا {{ offer.end_date|convert_to_persian_date }} در فاپوشاپ با وارد کردن کد تخفیف {{ offer.code }} در سبد خرید {{ offer.discount_amount }} درصد تخفیف دریافت کنید , فاپوشاپ عرضه کننده انواع ماگ های وارداتی و دست ساز سرامیکی">
    <meta property="og:title" content="جشنواره {{ offer.name }}">
    <meta property="og:description"
  content="از تاریخ {{ offer.start_date|convert_to_persian_date }} تا {{ offer.end_date|convert_to_persian_date }} در فاپوشاپ با وارد کردن کد تخفیف {{ offer.code }} در سبد خرید {{ offer.discount_amount }} درصد تخفیف دریافت کنید , فاپوشاپ عرضه کننده انواع ماگ های وارداتی و دست ساز سرامیکی">
">
    <meta property="og:image"
          content="{% if offer.image %}{{ offer.image.url }}{% else %}{% static 'assets/image/logo.png' %}{% endif %}">
    <meta name="twitter:title" content="جشنواره {{ offer.name }}">
    <meta name="twitter:description"
  content="از تاریخ {{ offer.start_date|convert_to_persian_date }} تا {{ offer.end_date|convert_to_persian_date }} در فاپوشاپ با وارد کردن کد تخفیف {{ offer.code }} در سبد خرید {{ offer.discount_amount }} درصد تخفیف دریافت کنید , فاپوشاپ عرضه کننده انواع ماگ های وارداتی و دست ساز سرامیکی">
">
    <meta name="twitter:image"
          content="{% if offer.image %}{{ offer.image.url }}{% else %}{% static 'assets/image/logo.png' %}{% endif %}">
{% endblock %}
{% block content %}


    <div class="bread-crumb pt-3" xmlns="http://www.w3.org/1999/html">
        <div class="container-fluid">
            <div class="content-box">
                <div class="container-fluid">
                    <nav aria-label="breadcrumb" class="my-lg-0 my-2">
                        <ol class="breadcrumb mb-0">
                            <li class="breadcrumb-item"><a href="{% url 'pages:index' %}" class="font-14 text-muted">خانه</a>
                            </li>
                            <li class="breadcrumb-item"><a href="{% url 'offers:offer_list' %}"
                                                           class="font-14 text-muted">جشنواره ها</a></li>
                            <li class="breadcrumb-item active main-color-one-color font-14"
                                aria-current="page">{{ offer.name }}
                            </li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>

    <!-- end breadcroumb -->

    <!-- start content -->

    <div class="content">
        <div class="container-fluid">
            <div class="row gy-3">
                <div class="col-lg-12">
                    <div class="content-box">
                        <div class="container-fluid">
                            <div class="blog-detail">
                                <div class="title-panel mb-2">
                                </div>
                                <div class="blog-post-title-items">
                                    <div class="blog-post-title-item">
                                        <img src="{% static 'assets/image/logo.png' %}" class="rounded-circle" alt="">
                                        <p class="text-muted">فاپو شاپ</p>
                                    </div>
                                </div>
                                <div class="blog-post-content">
                                    <div class="blog-post-content">
                                        <h4 class="title gold mb-2"> جشنواره {{ offer.name }}  </h4>
                                        <figure class="image-center">
                                            {% if offer.image %}
                                                <img class="aligncenter p-5"
                                                     src="{{ offer.image.url }}"
                                                     alt="{{ offer.name }}">
                                            {% else %}
                                                <img class="aligncenter p-5"
                                                     src=" {% static 'assets/image/logo.png' %} "
                                                     alt="{{ offer.name }}">

                                            {% endif %}
                                        </figure>
                                        <h6 class="pb-5">&nbsp;وضعیت جشنواره :
                                            <strong class="text-danger">{{ offer.offer_status }}</strong>
                                        </h6>
                                        <div class="d-flex p-5 justify-content-evenly border border-animate">
                                            <p class="d-flex align-items-center">
                                                <i class="fa-solid fa-clock fa-2x text-success me-2"></i>
                                                تاریخ شروع :
                                                <strong>{{ offer.start_date.date|convert_to_persian_date }}</strong>
                                            </p>
                                            <p class="d-flex align-items-center">
                                                <i class="fa-solid fa-clock fa-2x text-danger me-2 pt-1"></i>
                                                تاریخ پایان :
                                                <strong>{{ offer.end_date.date|convert_to_persian_date }}</strong>
                                            </p>
                                            <p class="d-flex align-items-center">
                                                <i class="fa-solid fa-percent fa-2x text-success me-2"></i>
                                                میزان تخفیف : <strong>{{ offer.discount_amount }} درصد </strong>
                                            </p>
                                        </div>
                                        {% if offer.is_active %}
                                            <div class="d-flex justify-content-center align-items-center"
                                                 style="height: 100px;">
                                                <h6 class="mx-auto p-3">از
                                                    تاریخ <strong
                                                            class="main-color-one-color">{{ offer.start_date.date|convert_to_persian_date }}</strong>
                                                    تا
                                                    تاریخ <strong
                                                            class="main-color-one-color">{{ offer.end_date.date|convert_to_persian_date }}</strong>
                                                    شما میتوانید در
                                                    <strong class="main-color-one-color"></strong>جشنواره {{ offer.name }}
                                                    با وارد کردن کد تخفیف "<strong
                                                            class="text-danger">{{ offer.code }}</strong>" در سبد
                                                    خرید محصولات خود به میزان<strong
                                                            class="text-danger"> {{ offer.discount_amount }}
                                                        درصد </strong> تخفیف
                                                    بگیرید </h6>
                                            </div>
                                        {% else %}
                                            <div class="d-flex justify-content-center align-items-center"
                                                 style="height: 100px;">
                                                <h6 class="text-center"><strong>این جشنواره منقضی شده است 😔</strong>
                                                </h6>
                                            </div>
                                        {% endif %}
                                        <p>&nbsp;</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>






    <!-- end related post -->


{% endblock %}

templates/offers/offers_list.html
{% extends "base.html" %}
{% load site_tags %}
{% load static %}
{% block title %}
    جشنواره های فروش
{% endblock %}
{% block tags %}
    <meta name="description"
          content="اطلاعات و کد های تخفیف جشنواره های فروش در فروشگاه ماگ و ملزومات آشپرخانه فاپوشاپ">
    <meta property="og:title" content="جشنواره های فروش">
    <meta property="og:description"
          content="اطلاعات و کد های تخفیف جشنواره های فروش در فروشگاه ماگ و ملزومات آشپرخانه فاپوشاپ">
    <meta property="og:image" content="
            {% if offers.0.image %}{{ offers.0.image.url }}{% else %}{% static 'assets/image/logo.png' %}{% endif %}">
    <meta name="twitter:title" content="جشنواره های فروش">
    <meta name="twitter:description"
          content="اطلاعات و کد های تخفیف جشنواره های فروش در فروشگاه ماگ و ملزومات آشپرخانه فاپوشاپ">
    <meta name="twitter:image" content="
            {% if offers.0.image %}{{ offers.0.image.url }}{% else %}{% static 'assets/image/logo.png' %}{% endif %}">
{% endblock %}
{% block content %}

    <div class="bread-crumb pt-3">
        <div class="container-fluid">
            <div class="content-box">
                <div class="container-fluid">
                    <nav aria-label="breadcrumb" class="my-lg-0 my-2">
                        <ol class="breadcrumb mb-0">
                            <li class="breadcrumb-item"><a href="{% url 'pages:index' %}"
                                                           class="font-14 text-muted">خانه</a>
                            </li>
                            <li class="breadcrumb-item active main-color-one-color font-14" aria-current="page"> جشنواره
                                های فروش
                            </li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <div class="gird-post-blog py-20">

        <div class="container-fluid">
            <div
                    class="header-content mb-4 bg-white shadow-box rounded-3 p-3 d-flex align-items-center justify-content-between flex-wrap">
                <div class="title d-flex align-items-center">

                    <h5 class="font-16 ms-3"> جشنواره های فروش <span
                            class="main-color-one-color d-inline-block"> فعال </span>
                    </h5>
                </div>
            </div>
        </div>

        <div class="container-fluid">
            <div class="row gy-3">
                {% for offer in offers %}
                    {% if offer.image %}
                        <div class="col-lg-3">
                            <div class="blog-item">
                                <a href="{% url 'offers:offer_detail' offer_id=offer.id %}">
                                    {% if offer.image %}
                                        <div class="image">
                                            <img src="{{ offer.image.url }}" alt="" class="img-fluid rounded-2"
                                                 style="object-fit: contain;">
                                        </div>
                                    {% else %}
                                        <div class="image">
                                            <img src="{% static 'assets/image/logo.png' %}" alt=""
                                                 class="img-fluid rounded-2" style="object-fit: contain;">
                                        </div>
                                    {% endif %}
                                    <div class="title">
                                        <div class="d-flex align-items-center justify-content-between">
                                            <div class="title-item">
                                                <i class="fa-solid fa-percent  fa-xl text-success"></i>
                                                <span class="font-12 danger-label">{{ offer.discount_amount }}</span>
                                            </div>
                                            <div class="title-item">
                                                <i class="bi bi-alarm me-1"></i>
                                                <span class="font-12">{{ offer.start_date.date|convert_to_persian_date }}</span>
                                                <span><strong> تا   </strong> </span>
                                                <i class="bi bi-alarm me-1"></i>
                                                <span class="font-12">{{ offer.end_date.date|convert_to_persian_date }}</span>
                                            </div>
                                        </div>
                                        <h4 class="font-16 text-overflow-1 h4"> {{ offer.name }}
                                        </h4>
                                    </div>
                                </a>
                            </div>
                        </div>
                    {% endif %}
                {% empty %}
                    <div class="d-flex justify-content-center align-items-center" style="height: 100px;">
                        <h6 class="text-center"><strong>در حال حاضر جشنواره فروش فعالی نداریم 😔</strong></h6>
                    </div>

                {% endfor %}
            </div>
        </div>
    </div>
    <div class="gird-post-blog py-20">

        <div class="container-fluid">
            <div
                    class="header-content mb-4 bg-white shadow-box rounded-3 p-3 d-flex align-items-center justify-content-between flex-wrap">
                <div class="title d-flex align-items-center">

                    <h5 class="font-16 ms-3"> جشنواره های فروش <span
                            class="main-color-one-color d-inline-block"> پیش رو </span>
                    </h5>
                </div>
            </div>
        </div>

        <div class="container-fluid">
            <div class="row gy-3">
                {% for offer in future_offers %}
                    {% if offer.image %}
                    <div class="col-lg-3">
                        <div class="blog-item">
                            <a href="{% url 'offers:offer_detail' offer_id=offer.id %}">
                                {% if offer.image %}
                                    <div class="image">
                                        <img src="{{ offer.image.url }}" alt="" class="img-fluid rounded-2"
                                             style="object-fit: contain;">
                                    </div>
                                {% else %}
                                    <div class="image">
                                        <img src="{% static 'assets/image/logo.png' %}" alt=""
                                             class="img-fluid rounded-2" style="object-fit: contain;">
                                    </div>
                                {% endif %}
                                <div class="title">
                                    <div class="d-flex align-items-center justify-content-between">
                                        <div class="title-item">
                                            <i class="fa-solid fa-percent  fa-xl text-success"></i>
                                            <span class="font-12 danger-label">{{ offer.discount_amount }}</span>
                                        </div>
                                        <div class="title-item">
                                            <i class="bi bi-alarm me-1"></i>
                                            <span class="font-12">{{ offer.start_date.date|convert_to_persian_date }}</span>
                                            <span><strong> تا   </strong> </span>
                                            <i class="bi bi-alarm me-1"></i>
                                            <span class="font-12">{{ offer.end_date.date|convert_to_persian_date }}</span>
                                        </div>
                                    </div>
                                    <h4 class="font-16 text-overflow-1 h4"> {{ offer.name }}
                                    </h4>
                                </div>
                            </a>
                        </div>
                    </div>
                    {% endif %}
                {% empty %}
                    <div class="d-flex justify-content-center align-items-center" style="height: 100px;">
                        <h6 class="text-center"><strong>متاسفانه در حال حاضر جشنواره ای پیش رو نداریم 😔</strong></h6>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="gird-post-blog py-20">

        <div class="container-fluid">
            <div
                    class="header-content mb-4 bg-white shadow-box rounded-3 p-3 d-flex align-items-center justify-content-between flex-wrap">
                <div class="title d-flex align-items-center">

                    <h5 class="font-16 ms-3"> جشنواره های فروش <span
                            class="main-color-one-color d-inline-block"> منقضی شده </span>
                    </h5>
                </div>
            </div>
        </div>

        <div class="container-fluid">
            <div class="row gy-3">
                {% for offer in out_dated_offers %}
                    {% if offer.image %}
                    <div class="col-lg-3">
                        <div class="blog-item">
                            <a href="{% url 'offers:offer_detail' offer_id=offer.id %}">
                                {% if offer.image %}
                                    <div class="image">
                                        <img src="{{ offer.image.url }}" alt="" class="img-fluid rounded-2"
                                             style="object-fit: contain;">
                                    </div>
                                {% else %}
                                    <div class="image">
                                        <img src="{% static 'assets/image/logo.png' %}" alt=""
                                             class="img-fluid rounded-2" style="object-fit: contain;">
                                    </div>
                                {% endif %}
                                <div class="title">
                                    <div class="d-flex align-items-center justify-content-between">
                                        <div class="title-item">
                                            <i class="fa-solid fa-percent  fa-xl text-success"></i>
                                            <span class="font-12 danger-label">{{ offer.discount_amount }}</span>
                                        </div>
                                        <div class="title-item">
                                            <i class="bi bi-alarm me-1"></i>
                                            <span class="font-12">{{ offer.start_date.date|convert_to_persian_date }}</span>
                                            <span><strong> تا   </strong> </span>
                                            <i class="bi bi-alarm me-1"></i>
                                            <span class="font-12">{{ offer.end_date.date|convert_to_persian_date }}</span>
                                        </div>
                                    </div>
                                    <h4 class="font-16 text-overflow-1 h4"> {{ offer.name }}
                                    </h4>
                                </div>
                            </a>
                        </div>
                    </div>
                    {% endif %}
                {% empty %}
                    <div class="d-flex justify-content-center align-items-center" style="height: 100px;">
                        <h6 class="text-center"><strong>فعلا جشنواره ای مدت زمانش گذشته باشه نداریم</strong></h6>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>


{% endblock %}