blog/urls.py
from . import views
from django.urls import path

app_name = "blog"

urlpatterns = [
    path("", views.blog_main_page, name="main"),
    #re_path(r'(?P<slug>[-\w]+)/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/', views.post_detail, name="post_detail"),

    path("details/<str:slug>/<int:year>/<int:month>/<int:day>/", views.post_detail, name="post_detail"),
    path("submit-comment/<int:post_id>/", views.submit_comment, name="submit_comment"),
    path("search/<str:query>/", views.search_post, name="search"),
    path("categories/<str:slug>/<int:cat_id>/", views.post_by_categories, name="post_by_categories"),

]

fapo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from accounts.sitemaps import StaticAccountsView
from blog.sitemaps import BlogPostsSitemap, BlogCommentsSitemap
from shop.sitemaps import CategorySitemap, ProductSitemap
from offers.sitemaps import OffersSitemap
from pages.sitemaps import PagesSiteMap
sitemaps = {
    "blog_posts": BlogPostsSitemap,
    "blog_comments": BlogCommentsSitemap,
    "accounts": StaticAccountsView,
    "shop_category": CategorySitemap,
    "products": ProductSitemap,
    "offers": OffersSitemap,
    "pages": PagesSiteMap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path("order/", include("orders.urls", namespace="orders")),  # Ensure `app_name` is set in `orders.urls`
    path("", include("pages.urls")),  # Home or general pages
    path("accounts/", include("accounts.urls", namespace="accounts")),  # Accounts app
    path("social-auth/", include("social_django.urls", namespace="social")),  # Social auth
    path("cart/", include("cart.urls", namespace="cart")),  # Shopping cart
    path("cities/", include("cities.urls", namespace="cities")),  # Cities app
    path("sms/", include("sms.urls", namespace="sms")),  # SMS app
    path("ticket/", include("tickets.urls", namespace="tickets")),  # Tickets app
    path("blog/", include("blog.urls", namespace="blog")),  # Blog app
    path("shop/", include("shop.urls", namespace="shop")),  # Shop app
    path("staff/", include("staff_area.urls", namespace="staff_area")),  # Staff area
    path("offers/", include("offers.urls", namespace="offers")),  # Offers app
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

app_name = "pages"

urlpatterns = [
    path("", views.index_page, name="index"),
    path("privacy-policy/", views.privacy_policy, name="privacy_policy"),
    path("سوالات-متداول/", views.frequency_asked_questions, name="frequency_asked_questions"),
    path("تماس-با-ما/", views.contact, name="contact"),
    path("قوانین-و-مقررات/", views.terms, name="terms"),
    path("درباره-ما/", views.about_us, name="about_us"),
    path("robots.txt", views.robots, name="robots_txt"),
]

sms/urls.py
from django.urls import path
from .views import send_otp

app_name = "sms"

urlpatterns = [
    path("send-otp/", send_otp, name="send_otp"),
]

blog/models.py
from django.db import models
from django.utils import timezone
from accounts.models import CustomUser
from django.urls import reverse
from taggit.managers import TaggableManager
from django.utils.text import slugify



class PostCategory(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)
    icon = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ["name"]
        indexes = [
            models.Index(fields=["name"])
        ]
        verbose_name = "category"
        verbose_name_plural = "categories"

    def get_absolute_url(self):
        return reverse("blog:post_by_categories", args=[self.slug, self.id])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name, allow_unicode=True)

        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)

class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    category = models.ForeignKey(PostCategory, related_name="posts", on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    subtitle = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date="publish", allow_unicode=True)
    author = models.ForeignKey(CustomUser,
                               on_delete=models.CASCADE,
                               related_name="blog_posts")
    body = models.TextField()
    tags = TaggableManager()
    image = models.ImageField(upload_to="post_images", null=True, blank=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)

    objects = models.Manager()  # The Default Manager
    published = PublishedManager()  # Our Custom Manager

    class Meta:
        ordering = ["-publish"]
        indexes = models.Index(fields=["-publish"]),

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[
            self.slug,
            self.publish.year,
            self.publish.month,
            self.publish.day,

        ])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title, allow_unicode=True)

        super().save(*args, **kwargs)

class PostSection(models.Model):
    post = models.ForeignKey(Post, related_name="sections", on_delete=models.CASCADE)
    subtitle = models.CharField(max_length=250)
    image = models.ImageField(upload_to="post_section_images", null=True, blank=True)
    body = models.TextField()

    class Meta:
        ordering = ["id"]

    def __str__(self):
        return f"Section: {self.subtitle} (Post: {self.post.title})"

class PostComment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, related_name='comments', on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False)

    parent = models.ForeignKey('self', null=True, blank=True, related_name='replies', on_delete=models.CASCADE)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Comment by {self.user} on {self.post}'

    @property
    def is_reply(self):
        """Return True if the comment is a reply to another comment."""
        return self.parent is not None

blog/forms.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField()


class CommentForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 7,
        'placeholder': 'دیدگاه شما',
        'class': 'form-control',
        'id': 'commentbody',
        'required': 'required',
    }))


blog/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Count
from .models import PostCategory, Post, PostComment
import redis
from .forms import SearchForm, CommentForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from django.contrib.postgres.search import SearchVector
from shop.models import Product
from random import sample
import os
from django.conf import settings




r = redis.Redis.from_url(os.getenv("REDIS_URL", "redis://redis:6379/0"))




def blog_main_page(request):
    page = request.GET.get('page', 1)
    try:
        int(page)
    except ValueError or TypeError:
        page = 1

    post_only = request.GET.get('post_only')
    post_ranking = r.zrange("post_ranking", 0, -1)
    post_ranking_ids = [int(post_id) for post_id in post_ranking]
    most_viewed_post = list(Post.objects.filter(id__in=post_ranking_ids))
    most_viewed_post.sort(key=lambda x: post_ranking_ids.index(x.id))
    form = SearchForm()
    all_categories = PostCategory.objects.all()
    post_list = Post.published.all()
    paginator = Paginator(post_list, 8)  # Show 8 posts per page

    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
        post_list = paginator.page(1)
    except EmptyPage:
        if post_only:
            return HttpResponse("")
        post_list = paginator.page(paginator.num_pages)

    context = {
        "form": form,
        "all_categories": all_categories,
        "post_list": post_list,
        "most_viewed_post": most_viewed_post,
    }

    if post_only:
        return render(request, "blog/post_list.html", context)
    else:
        return render(request, "blog/blog.html", context)


def post_detail(request, year, month, day, slug):
    form = SearchForm()
    comment_form = CommentForm()
    post = get_object_or_404(Post, status=Post.Status.PUBLISHED,
                             slug=slug, publish__year=year,
                             publish__month=month, publish__day=day)
    try:
        post_comments = PostComment.objects.filter(post=post, parent=None)
    except PostComment.DoesNotExist:
        post_comments = None

    r.zincrby("post_ranking", 1, post.id)
    must_sell_products = list(Product.objects.filter(available=True).order_by("-created"))
    must_sell_products = sample(must_sell_products, 4)

    post_ranking = r.zrange("post_ranking", 0, -1)
    if post_ranking:
        post_ranking_ids = [int(post_id) for post_id in post_ranking]
        most_viewed_post = list(Post.objects.filter(id__in=post_ranking_ids).exclude(id=post.id))
        most_viewed_post.sort(key=lambda x: post_ranking_ids.index(x.id))
        most_viewed_post = list(most_viewed_post)
        most_viewed_post = most_viewed_post[0]
    else:
        most_viewed_post = None
    section = post.sections.all()
    latest_posts = Post.published.all().exclude(id=post.id)[:6]
    total_views = r.incr(f"post: {post.id}:views")
    post_tags_ids = post.tags.values_list("id", flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count("tags")).order_by("-same_tags", "-publish")

    context = {
        "post" : post,
        "form": form,
        "total_views": total_views,
        "similar_posts": similar_posts,
        "post_comments": post_comments,
        "comment_form" : comment_form,
        "latest_posts": latest_posts,
        "most_viewed_post": most_viewed_post,
        "must_sell_products": must_sell_products,
        "section": section
    }
    return render(request, "blog/post_details.html", context)


@login_required
def submit_comment(request, post_id):
    print(f"this is parent id : {request.POST.get('parent_id')}")
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = PostComment.objects.create(post=post, body=comment_form.cleaned_data["comment"],user=request.user)
            if request.user.is_staff:
                parent_id = request.POST.get('parent_id')
                if parent_id:
                    parent_comment = PostComment.objects.get(id=parent_id)
                    new_comment.parent = parent_comment

            new_comment.save()


    return redirect("blog:post_detail",year=post.publish.year, month=post.publish.month, day=post.publish.day, slug=post.slug)

def search_post(request, query):
    page = request.GET.get('page')
    post_only = request.GET.get('post_only')

    if query:
        form = SearchForm(request.GET)
        if form.is_valid():
            post_list = Post.published.annotate(search=SearchVector("title", "body", "subtitle")).filter(search=query)

        else:
            post_list = Post.published.annotate(search=SearchVector("title", "body", "subtitle")).filter(search=query)

        paginator = Paginator(post_list, 8)  # Show 8 posts per page

        try:
            post_list = paginator.page(page)
        except PageNotAnInteger:
            post_list = paginator.page(1)
        except EmptyPage:
            if post_only:
                return HttpResponse("")
            post_list = paginator.page(paginator.num_pages)

        context = {
            "post_list": post_list,
            "query": query,
        }

        if post_only:
            return render(request, "blog/post_list.html", context)
        else:
            return render(request, "blog/search_results.html", context)
    else:
        raise PermissionDenied


def post_by_categories(request, cat_id, slug):
    page = request.GET.get('page')
    post_only = request.GET.get('post_only')
    category = get_object_or_404(PostCategory, id=cat_id, slug=slug)
    post_list = Post.objects.filter(category=category)
    paginator = Paginator(post_list, 8)  # Show 8 posts per page
    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
        post_list = paginator.page(1)
    except EmptyPage:
        if post_only:
            return HttpResponse("")
        post_list = paginator.page(paginator.num_pages)

    context = {
        "post_list": post_list,
        "category":category,
    }

    if post_only:
        return render(request, "blog/post_list.html", context)
    else:
        return render(request, "blog/blog_category.html", context)


templates/blog/blog.html
{% extends 'base.html' %}
{% load site_tags %}
{% load static %}
{% block title %}
    بلاگ
{% endblock %}
{% block tags %}
    <meta name="description" content="
{% for cat in all_categories %}
    {{ cat.name }} , 
{% endfor %}
">
    <meta property="og:title" content="بلاگ فاپوشاپ جدیدترین مقالات">
    <meta property="og:description" content="{% for cat in all_categories %}
    {{ cat.name }} , 
{% endfor %}">
    <meta property="og:image" content="{% static 'assets/image/banner-blog.jpg' %}">
    <meta name="twitter:title" content="بلاگ فاپوشاپ جدیدترین مقالات">
    <meta name="twitter:description" content="{% for cat in all_categories %}
    {{ cat.name }} , 
{% endfor %}">
    <meta name="twitter:image" content="{% static 'assets/image/banner-blog.jpg' %}">
{% endblock %}
{% block content %}

    <div class="bread-crumb pt-3">
        <div class="container-fluid">
            <div class="content-box">
                <div class="container-fluid">
                    <nav aria-label="breadcrumb" class="my-lg-0 my-2">
                        <ol class="breadcrumb mb-0">
                            <li class="breadcrumb-item"><a href="{% url 'pages:index' %}" class="font-14 text-muted">خانه</a>
                            </li>
                            <li class="breadcrumb-item active main-color-one-color font-14" aria-current="page">وبلاگ
                            </li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>

    <!-- end breadcroumb -->

    <!-- start content -->

    <div class="content">

        <!-- start header blog -->

        <div class="container-fluid">
            <div class="row gy-3">
                <div class="col-lg-3">
                    <div class="content-box">
                        <div class="container-fluid">
                            <div class="side-right-blog">
                                <div class="search-form">
                                    <form id="search-form" action="" method="get"
                                          onsubmit="return searchRedirect(event)">
                                        {% csrf_token %}
                                        <div class="search-filed">
                                            <input type="text" placeholder="جستجوی در مقالات بلاگ ..."
                                                   class="form-control search-input"
                                                   name="query" id="query">
                                            <button type="submit" class="btn search-btn main-color-one-bg rounded-pill">
                                                <i class="bi bi-search"></i>
                                            </button>
                                        </div>
                                    </form>
                                </div>
                                <div class="navbar-blog">
                                    <nav class="navbar">
                                        <ul class="navbar-nav">
                                            {% for cat in all_categories %}
                                                <li class="nav-item mco-hover"><a href="{{ cat.get_absolute_url }}"
                                                                                  class="nav-link">{{ cat.icon|safe }} {{ cat.name }}
                                                    ({{ cat.posts.all|length }})</a>
                                                </li>
                                            {% endfor %}

                                        </ul>
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="side-left-blog">
                        <div class="row gy-3">
                            <div class="col-12">
                                <a href="">
                                    <img src="{% static 'assets/image/banner-blog.jpg' %}"
                                         class="img-fluid shadow-box rounded-4" alt="">
                                </a>
                            </div>
                            {% if most_viewed_post|length != 0 %}
                                {% if most_viewed_post.0 %}
                                    <div class="col-md-3">
                                        <div class="blog-news-item">
                                            <a href="{{ most_viewed_post.0.get_absolute_url }}">
                                                <img src="{{ most_viewed_post.0.image.url }}" alt="" class="img-fluid">
                                                <div class="desc">
                                                    <h3 class="title">{{ most_viewed_post.0.title }} </h3>
                                                    <div class="date">
                                                        <span class="text-date">{{ most_viewed_post.0.created.date|convert_to_persian_date }}</span>
                                                        <i class="bi bi-arrow-left"></i>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                {% endif %}
                                {% if most_viewed_post.1 %}
                                    <div class="col-md-6">
                                        <div class="blog-news-item">
                                            <a href="{{ most_viewed_post.1.get_absolute_url }}">
                                                <img src="{{ most_viewed_post.1.image.url }}" alt="" class="img-fluid">
                                                <div class="desc">
                                                    <h3 class="title">{{ most_viewed_post.1.title }}</h3>
                                                    <div class="date">
                                                        <span class="text-date">{{ most_viewed_post.1.created.date|convert_to_persian_date }}</span>
                                                        <i class="bi bi-arrow-left"></i>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                {% endif %}
                                {% if most_viewed_post.2 %}
                                    <div class="col-md-3">
                                        <div class="blog-news-item">
                                            <a href="{{ most_viewed_post.2.get_absolute_url }}">
                                                <img src="{{ most_viewed_post.2.image.url }}" alt="" class="img-fluid">
                                                <div class="desc">
                                                    <h3 class="title">{{ most_viewed_post.2.title }}</h3>
                                                    <div class="date">
                                                        <span class="text-date">{{ most_viewed_post.2.created.date|convert_to_persian_date }}</span>
                                                        <i class="bi bi-arrow-left"></i>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- end header blog -->

        <!-- start top post blog -->

        <div class="blog-slider site-slider site-slider-sm py-20">

            <div class="container-fluid">
                <div
                        class="header-content mb-4 bg-white shadow-box rounded-3 p-3 d-flex align-items-center justify-content-between flex-wrap">
                    <div class="title d-flex align-items-center">
                        <h5 class="font-16 ms-3">پربازدید ترین مطالب <span class="main-color-one-color d-inline-block">وبلاگ</span>
                        </h5>
                    </div>
                </div>
            </div>

            <div class="parent">
                <div class="container-fluid">
                    <div class="swiper product-slider-swiper">
                        <div class="swiper-wrapper">
                            {% include 'swapers/blog_swaper.html' with posts=most_viewed_post %}
                        </div>
                        <div class="swiper-button-next"></div>
                        <div class="swiper-button-prev"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="gird-post-blog py-20">

            <div class="container-fluid">
                <div
                        class="header-content mb-4 bg-white shadow-box rounded-3 p-3 d-flex align-items-center justify-content-between flex-wrap">
                    <div class="title d-flex align-items-center">
                        <h5 class="font-16 ms-3">آخرین مطالب <span
                                class="main-color-one-color d-inline-block">وبلاگ</span>
                        </h5>
                    </div>
                </div>
            </div>

            <div class="container-fluid">
                <div class="row gy-3" id="product-list">
                    {% include 'blog/post_list.html' with post_list=post_list %}

                </div>
            </div>
        </div>

        <!-- end latest post  -->


    </div>

    <!-- end content -->


    <script>
        let page = 1;
        let emptyPage = false;
        let blockRequest = false;

        function getMargin() {
            if (window.innerWidth <= 768) {
                // Smaller margin for mobile devices
                return 1200;
            } else {
                // Default margin for larger screens
                return 600;
            }
        }

        window.addEventListener('scroll', function () {
            const margin = document.body.clientHeight - window.innerHeight - getMargin();
            if (window.pageYOffset > margin && !emptyPage && !blockRequest) {
                blockRequest = true;
                page += 1;
                fetch('?post_only=1&page=' + page)
                    .then(response => response.text())
                    .then(html => {
                        if (html === '') {
                            emptyPage = true;
                        } else {
                            const postList = document.getElementById('product-list');
                            postList.insertAdjacentHTML('beforeend', html);
                            blockRequest = false;
                        }
                    });
            }
        });

        // Trigger the initial scroll event to load more posts if needed
        window.dispatchEvent(new Event('scroll'));


    </script>
    <script>
        function searchRedirect(event) {
            event.preventDefault();  // Prevent default form submission
            const query = document.getElementById('query').value;  // Get the search query input
            if (query) {
                const url = "{% url 'blog:search' query='QUERY_PLACEHOLDER' %}".replace('QUERY_PLACEHOLDER', encodeURIComponent(query));
                window.location.href = url;  // Redirect to the custom search URL
            }
        }
    </script>


{% endblock %}

templates/blog/blog_category.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
وبلاگ | دسته بندی : {{  category.name }}
{% endblock %}
    {% block tags %}
        <meta name="description" content="فاپوشاپ پست های بلاگ با دسته بندی : {{  category.name }}">
        <meta property="og:title" content="وبلاگ | دسته بندی : {{  category.name }}">
        <meta property="og:description" content="فاپوشاپ پست های بلاگ با دسته بندی : {{  category.name }}">
        <meta property="og:image" content="{% static 'assets/image/logo.png' %}">
        <meta name="twitter:title" content="وبلاگ | دسته بندی : {{  category.name }}">
        <meta name="twitter:description" content="فاپوشاپ پست های بلاگ با دسته بندی : {{  category.name }}">
        <meta name="twitter:image" content="{% static 'assets/image/logo.png' %}">
    {% endblock %}
{% block content %}
    <div class="bread-crumb pt-3">
        <div class="container-fluid">
            <div class="content-box">
                <div class="container-fluid">
                    <nav aria-label="breadcrumb" class="my-lg-0 my-2">
                        <ol class="breadcrumb mb-0">
                            <li class="breadcrumb-item"><a href="{% url 'pages:index' %}" class="font-14 text-muted">خانه</a>
                            </li>
                            <li class="breadcrumb-item"><a href="{% url 'blog:main' %}"
                                                           class="font-14 text-muted">بلاگ</a></li>
                            <li class="breadcrumb-item active main-color-one-color font-14" aria-current="page"> دسته بندی : 
                                 {{ category.name }}
                            </li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>

    <!-- end breadcroumb -->

    <!-- start content -->

    <div class="content">


        <!-- start latest post  -->

        <div class="gird-post-blog py-20">
            {% if post_list|length != 0 %}

                <div class="container-fluid">
                    <div
                            class="header-content mb-4 bg-white shadow-box rounded-3 p-3 d-flex align-items-center justify-content-between flex-wrap">
                        <div class="title d-flex align-items-center">
                            {{ category.icon|safe }}
                            <h5 class="font-16 ms-3"> دسته بندی : <span
                                    class="main-color-one-color d-inline-block">  {{ category.name }}</span>
                            </h5>
                        </div>
                    </div>
                </div>
            {% else %}
                <div class="container-fluid">
                    <div
                            class="header-content mb-4 bg-white shadow-box rounded-3 p-3 d-flex align-items-center justify-content-between flex-wrap">
                        <div class="title d-flex align-items-center">
                            <h5 class="font-16 ms-3"> متاسفانه در این دسته بندی پستی موجود نیست<span
                                    class="main-color-one-color d-inline-block"></span>
                            </h5>
                        </div>
                    </div>
                </div>
            {% endif %}

            <div class="container-fluid">
                {% if post_list|length != 0 %}
                    <div class="row gy-3" id="product-list">
                        {% include 'blog/post_list.html' with post_list=post_list %}
                    </div>
                {% endif %}
            </div>


        </div>
    </div>
    <script>
        let page = 1;
        let emptyPage = false;
        let blockRequest = false;
        window.addEventListener('scroll', function () {
            const margin = document.body.clientHeight - window.innerHeight - 400;
            if (window.pageYOffset > margin && !emptyPage && !blockRequest) {
                blockRequest = true;
                page += 1;
                fetch(`?post_only=1&page=${page}`)
                    .then(response => response.text())
                    .then(html => {
                        if (html === '') {
                            emptyPage = true;
                        } else {
                            const postList = document.getElementById('product-list');
                            postList.insertAdjacentHTML('beforeend', html);
                            blockRequest = false;
                        }
                    });
            }
        });

        // Trigger the initial scroll event to load more posts if needed
        window.dispatchEvent(new Event('scroll'));
    </script>
{% endblock %}
